name: build-stable
on: push
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: build.pkr.hcl
      - name: Set up Packer
        uses: hashicorp-contrib/setup-packer@v1 
      - name: Set up QEMU
        run: sudo apt-get install -y qemu-system-x86
      - name: Set up network bridge
        run: |
          sudo mkdir -p /etc/systemd/network
          echo "[NetDev]\nName=br0\nKind=bridge" | sudo tee /etc/systemd/network/br0.netdev
          echo "[Match]\nName=br0\n\n[Network]\nDHCPServer=yes\nAddress=10.0.2.2/24\nIPForward=ipv4" | sudo tee /etc/systemd/network/br0.network
          sudo systemctl restart systemd-networkd
          ip a
      - name: Build Artifact
        run: packer build -color=false -on-error=abort -parallel-builds=1 build.pkr.hcl
        env:
          PKR_VAR_xwiki_version: "13.9"
          PKR_VAR_vagrant_cloud_access_token: ${{ secrets.VAGRANT_CLOUD_ACCESS_TOKEN }}
          PACKER_LOG: 1
