name: build-stable
on: push
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y virtualbox virtualbox-ext-pack qemu-system-x86
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: build.pkr.hcl
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -parallel-builds=1 -var 'xwiki_version=13.9' -var 'vagrant_cloud_access_token=somethingsomethingsomething'"
          target: build.pkr.hcl
        env:
          PACKER_LOG: 1
